baseURL: https://exist2021.github.io
languageCode: en-us
title: Manoj Nayak
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Articulation ✍️
        Content: Random aticulation of thoughts

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/exist2021"
        - name: "youtube"
          url: "https://instagram.com/manojnayakdotcom"
        - name: "twitter"
          url: "https://twitter.com/manojnayak"
        - name: "kofi" 
          url: "https://https://linkedin.com/manojrnayak"
        - name: "rss"
          url: "https://manojnayak.com/index.xml"
    ShowReadingTime: true
    author: "One Nice Person"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20
