baseURL: https://manoj.buzz
languageCode: en-us
title: Manoj Nayak's Personal Blog
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Articulation ✍️
        Content: Random articulation of thoughts

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/exist2021"
        - name: "Instagram"
          url: "https://instagram.com/manojnayakdotcom"
        - name: "twitter"
          url: "https://twitter.com/manojnayak"
        - name: "linkedin" 
          url: "www.linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=manojrnayak"
        - name: "rss"
          url: "https://manojnayak.com/index.xml"
    ShowReadingTime: true
    author: "Manoj Nayak"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20
googleAnalytics: G-7E5K4RLK3E
